spring:
  application:
    name: my-eureka
#  security:
#    user:
#      name: admin
#      password: admin
  profiles:
    active: master

eureka:
  client:
    # 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责是维护服务实例，并不需要去检索服务，应该是服务向注册中心检索服务，所以也设置为false
    fetch-registry: false



